name: Jest Tests

on: push

jobs:
  Jest tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: npm install 
        run: npm ci
      - name: run tests
        run: npm run test-build